### ISSUE TITLE
Colecovision Controller Menu Image Broken/Invalid

### ISSUE THREAD

**Issue by kamshaft** [RetroPie/es-theme-carbon#12]
The default Colecovision controller image is not functional for the carbon theme.

I've attached a functioning one. 
[controller.zip](https://github.com/RetroPie/es-theme-carbon/files/285543/controller.zip)

**Comment by HerbFargus** [comment]
should be resolved as of https://github.com/RetroPie/es-theme-carbon/commit/c941d77e141c5db5fd1e4ef6e1a5970dd3d5c558 thanks. let me know if it doesnt work.
