### ISSUE TITLE
Change metadata label

### ISSUE THREAD

**Issue by padremayi** [RetroPie/es-theme-carbon#17]
How can we change metadata label?
How is the label "DEVELOPER" associated to the gamelist.xml tag <developer>?
How can I change "LAST PLAYED" with other stuff, like "BLA BLA BLA"?

I tried to change mld_label in carbon.xml and in theme.xml without success.
I don't understand where this line of text are.

Thanks

**Comment by joolswills** [comment]
Please use the retropie forum for help with theming etc.
