### ISSUE TITLE
Game and Watch logo is black..

### ISSUE THREAD

**Issue by Th4nat0s** [RetroPie/es-theme-carbon#22]
But black on black on item list is not visible.

**Comment by joolswills** [comment]
This is resolved now.

**Comment by Th4nat0s** [comment]
Nice, Which commit ? I don't find it..

**Comment by Th4nat0s** [comment]
houps sorry found it
https://github.com/RetroPie/es-theme-carbon/commit/bfe90d42a53c1a98287f76a142f25a091b029d82
