### ISSUE TITLE
Carbon crashes ES

### ISSUE THREAD

**Issue by duiz** [RetroPie/es-theme-carbon#29]
I downloaded the latest master of es-theme-carbon, but whenever I try to switch to it via UI settings it causes ES to crash. If I change the es_settings directly to use Carbon, it automatically just switches to simple instead.

Is this a known issue with carbon? I haven't made any modifications, and I am using the latest jdrassa win build. The same happens when I use older builds as well.

![carbon](https://cloud.githubusercontent.com/assets/7563543/25781178/50bb4d72-3336-11e7-8356-5f6b9c52fae9.jpg)

**Comment by joolswills** [comment]
It's probably related to that build of ES - sorry but this is a RetroPie repository, so I cannot help with 3rd party ES builds (We don't support windows).
