### ISSUE TITLE
[request] TG16 theme

### ISSUE THREAD

**Issue by BenWlson** [RetroPie/es-theme-carbon#4]
Please add a TG16 theme for those of us from the US who remember the TurboGrafx16 and not the PC Engine.

I see that in the pcengine/art there is a tg16.svg. I created a new folder called TG16.. copied the theme.xml file over, copied the controller.svg file over, and moved the tg16.svg to system.svg.

I got it all to work after changing my es_systems.cfg file to use theme TG16 instead of pcengine and it all worked. I just cannot figure out how to do the whole fork, commit, pull request thing with github to do this change myself. (A youtube video explaining how to do that would be great!)

Adding this theme change ability will mimic the way the genesis/megadrive theming is set up.

**Comment by HerbFargus** [comment]
There you go https://github.com/RetroPie/es-theme-carbon/pull/5 thanks for the input. let me know if it isnt working.

**Comment by BenWlson** [comment]
Thanks. I updated the wiki similar to the megadrive/genesis.

**Comment by HerbFargus** [comment]
Appreciate it. If people are going to be making custom edits to es_systems.cfg it might be worth noting on the wiki a diff save location for es_systems.cfg as mentioned here:

https://github.com/RetroPie/RetroPie-Setup/wiki/EmulationStation#my-es_sytemscfg-is-being-overwritten-on-updates
